### ISSUE TITLE
Module not found after electron-packager run

### ISSUE THREAD

**Issue by ahallicks** [paulcbetts/node-system-idle-time#3]
I'm not sure if this is a problem with this `node_module` or electron-packager but after packing my app I get the error "Module not found: '@paulcbetts/system-idle-time'" on Windows.

I unpacked the app.asar file generated by electron-packager and it does not get created there. But running the app from the command line works fine.

I did make sure to run electron-rebuild after install and that worked fine as I've got a couple of other modules that need to be rebuilt too.

**Comment by angvp** [comment]
@ahallicks I think this is pretty abbandoned, I'm facing a similar issue after doing lot of wizard commands to rebuild everything, I got this:

    TypeError: Cannot read property 'getIdleTime' of undefined

Did you found any solution? or did you implemented another package?

**Comment by ahallicks** [comment]
I've now switched to `electron-builder` to package my app and have not have any issues with the module not being found. I'm sorry I can't be of more help but it now 'just works' perfectly fine.
